[issue-6] [API] 회원 테이블 설계
dev-team-avengers/chamomile pull request #15
Opened 2022-08-14 05:42 UTC by kimkoungho

user + profile 테이블 설계

2022-08-14 08:20 UTC, YoungWukJeon requested changes

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +            fun of(value: Int): State {
매개변수가 하나 뿐이라면 `from` 이 어떨까요?

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/exception/IllegalEnumValueException.kt
> +class IllegalEnumValueException(message: String) : RuntimeException(message) {
의미적으로 `IllegalArgumentException`을 상속받는건도 괜찮지 않을까요?
[링크](https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalArgumentException.html)

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/test/kotlin/team/avengers/chamomile/domain/user/UserRepositoryTest.kt
> +    fun createTest() {
테스트의 목적이 쉽게 유추 가능한 메서드명이지만 일관성 있게
어떤 목적의 테스트인지 한글로 풀어주시는 것도 좋을 거 같아요.
ex) **메서드명** or `@DisplayName()` 사용

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/common/IntValueEnum.kt
> +import javax.persistence.Converter
사용되고 있지 않은 import문인거 같은데 제거하는게 좋을거 같아요

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +            fun of(value: Int): JoinType {
매개변수가 하나 뿐이라면 from 이 어떨까요?

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +    @Convert(converter = UserStatusConverter::class)
@Converter 생성하는 곳에서 옵션을 통해서 자동으로 컨버팅 설정을 할 수 있었던거 같은데
이 클래스에 종속된 Converter라면 자동 설정을 하고 @Convert 어노테이션을 제거해도 될 거 같아요.

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +    @Convert(converter = UserStatusConverter::class)
클래스명이 `State` 인데 컨버터가 `Status`로 되어있네요. 변경 부탁드려요.

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +    enum class JoinType(private val value: Int) {
DB상에서 **char(1)** 형태로 정의하신 거 같은데 여기서는 **Int** 타입으로 받고 있네요.
`CharValueEnum` 인터페이스를 정의하고 **Char** 타입으로 변경하는게 좋을거 같아요.

2022-08-14 08:20 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +        GOOGLE(3);
**Char** 타입으로 변경함에따라 `1, 2, 3`보다는
ex) `DEFAULT('D')`, `KAKAO('K')`, `GOOGLE('G')` 이런 형태로 변경하면 좋을거 같아요.

2022-08-21 05:21 UTC, kimkoungho commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +    @Convert(converter = JoinTypeConverter::class)
자동으로 컨버팅 등록 해주는 `@Converter(autoApply = true)` 로 등록하면 될 것 같다고 얘기한것 같은데 ..
그렇게 등록하면 개인적으로 JoinTypeConverter 참조되는  부분이 어디인지 찾기 쉽지 않을 것 같아 
JoinTypeConverter 가 특정 Entity 에만 종속되면 큰 문제가 없을 수 있지만 여러 Entity 에 참조되는 케이스가 있으면 해당 타입을 사용하는 부분을 따라가야 될 것 같아서 ...

2022-08-21 05:23 UTC, kimkoungho commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +            fun of(value: Int): JoinType {
@YoungWukJeon 
리뷰 내용 수정했음

2022-08-21 05:23 UTC, kimkoungho commented on domain/src/test/kotlin/team/avengers/chamomile/domain/user/UserRepositoryTest.kt
> +    fun createTest() {
@YoungWukJeon 
리뷰 내용 수정했음

2022-08-21 05:23 UTC, kimkoungho commented on domain/src/main/kotlin/team/avengers/chamomile/domain/exception/IllegalEnumValueException.kt
> +class IllegalEnumValueException(message: String) : RuntimeException(message) {
@YoungWukJeon 
리뷰 내용 수정했음

2022-08-21 05:44 UTC, YoungWukJeon commented on domain/src/main/kotlin/team/avengers/chamomile/domain/user/UserEntity.kt
> +    @Convert(converter = JoinTypeConverter::class)
JoinTypeConverter가 다른 곳에서 사용될 상황이 있을까요? 그렇다면 UserEntity 파일로 같이 가지고 있는게 좀 이상할 거 같아서요.

2022-08-24 14:05 UTC, YoungWukJeon approved these changes

2022-08-24 14:06 UTC, merged